version: "2"
services: 
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306

    adminer:
        image: adminer
        container_name: adminer_mysql
        ports: 
            - 8081:8080
        links: 
            - mysql